config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    authenticated :user do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  resources :users
  resources :needs
  resources :activities
  resources :own_activities
end

app/models/activity.rb
class Activity < ApplicationRecord
	has_many :user_activities
  has_many :users, through: :user_activities

  def add_member user
  	self.users << user
  end

  def has_already_added? user
  	self.user_activities.where(user_id: user.id).present?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/need.rb
class Need < ApplicationRecord
end

app/models/own_activity.rb
class OwnActivity < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :users

	def own_grade
		grade.to_s + " - " + section + " " + year
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :section, optional: true    
  has_many :user_activities
  has_many :activities, through: :user_activities

  def full_name
    begin
      first_name + " " + last_name
    rescue
      ""
    end
  end

  def own_grade
    begin
      self.section.own_grade
    rescue
      ""
    end
  end
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
	belongs_to :user
	belongs_to :activity
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	 layout "admin" 
  
  before_action :set_need, only: [:show, :edit, :update]

  def index
    @activities = Activity.all
  end

  def show
    if @activity.has_already_added? current_user
      redirect_to activities_path, alert: 'You has already been added to this activity'  
    else
      @activity.add_member current_user
      redirect_to activities_path, notice: 'You has been added correctly to this activity'  
    end
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new activity_params
    if @activity.save
      redirect_to activities_path, notice: 'Activity was successfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @activity.assign_attributes activity_params
    if @activity.save
      redirect_to activities_path, notice: 'Activity was successfully created'
    else
      render :edit
    end
  end

  private
  def activity_params
    params.require(:activity).permit(:name, :description, :show_time, :value, :place)
  end

  def set_need
    @activity = Activity.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resources)
  	root_path	
  end

  def after_sign_out_path_for(resources)
  	new_user_session_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	layout "admin" 
  before_action :authenticate_user!

	def index
		
	end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  layout "admin" 
  
  before_action :set_need, only: [:edit, :update]

  def index
    @needs = Need.all
  end

  def new
    @need = Need.new
  end

  def create
    @need = Need.new need_params
    if @need.save
      redirect_to needs_path, notice: 'Need was successfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @need.assign_attributes need_params
    if @need.save
      redirect_to needs_path, notice: 'Need was successfully created'
    else
      render :edit
    end
  end

  private
  def need_params
    params.require(:need).permit(:name, :description, :sales_place, :value)
  end

  def set_need
    @need = Need.find params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout "admin" 
	before_action :set_user, only: [:edit, :update]

	def index
		@users = User.all
	end

	def new
	end

	def create
	end

	def edit
	end

	def update
		@user.assign_attributes user_params
		if @user.save
			redirect_to users_path, notice: 'User was successfully updated'
		else
			render :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :phone)
	end

	def set_user
		@user = User.find params[:id]
	end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/helpers/own_activities_helper.rb
module OwnActivitiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FuerzaChicho!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <%= render "layouts/home/navbar" %>
      <div id="page-wrapper">        
        <%= render "layouts/home/messages" %>
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChichoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home/_messages.html.erb
<div id="alert-messages">
	<% if !flash[:notice].blank? %>
		<div class="alert alert-success alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= flash[:notice].html_safe %>
		</div>
	<% end %>
	<% if !flash[:information].blank? %>
		<div class="alert alert-info alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= flash[:information].html_safe %>
		</div>
	<% end %>
	<% if !flash[:warning].blank? %>
		<div class="alert alert-warning alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= flash[:warning].html_safe %>
		</div>
	<% end %>
	<% if !flash[:alert].blank? %>
		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= flash[:alert].html_safe %>
		</div>
	<% end %>
</div>

app/views/layouts/home/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

  </div>
      <%= link_to root_path, class: 'navbar-brand' do %>
        Todos por Chicho!
      <% end %>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user-circle"></i><%=  current_user.email %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to edit_user_path(current_user) do %>
              </i> Profile</a>
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-power-off"></i> Log Out
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">
        <li>
          <%= link_to users_path do %>
              <i class="fa fa-fw fa-users"></i>
              Usuarios
          <% end %>
        </li>
        <li>
          <%= link_to needs_path do %>
              <i class="fa fa-fw fa-shopping-basket"></i>
              Necesidades
          <% end %>
        </li>  
        <li>
          <%= link_to activities_path do %>
              <i class="fa fa-fw fa-calendar"></i>
              Actividades
          <% end %>
        </li>     
        <li>
          <%= link_to own_activities_path do %>
              <i class="fa fa-fw fa-calendar-check-o"></i>
              Mis Actividades
          <% end %>
        </li>             
      </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>