config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    authenticated :user do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  resources :users
  resources :needs
  resources :activities
  resources :own_activities
end

app/models/activity.rb
class Activity < ApplicationRecord
	has_many :user_activities
  has_many :users, through: :user_activities

  def add_member user
  	self.users << user
  end

  def has_already_added? user
  	self.user_activities.where(user_id: user.id).present?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/need.rb
class Need < ApplicationRecord
end

app/models/own_activity.rb
class OwnActivity < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :users

	def own_grade
		grade.to_s + " - " + section + " " + year
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :section, optional: true    
  has_many :user_activities
  has_many :activities, through: :user_activities

  def full_name
    begin
      first_name + " " + last_name
    rescue
      ""
    end
  end

  def own_grade
    begin
      self.section.own_grade
    rescue
      ""
    end
  end
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
	belongs_to :user
	belongs_to :activity
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	 layout "admin" 
  
  before_action :set_need, only: [:show, :edit, :update]

  def index
    @activities = Activity.all
  end

  def show
    if @activity.has_already_added? current_user
      redirect_to activities_path, alert: 'You has already been added to this activity'  
    else
      @activity.add_member current_user
      redirect_to activities_path, notice: 'You has been added correctly to this activity'  
    end
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new activity_params
    if @activity.save
      redirect_to activities_path, notice: 'Activity was successfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @activity.assign_attributes activity_params
    if @activity.save
      redirect_to activities_path, notice: 'Activity was successfully created'
    else
      render :edit
    end
  end

  private
  def activity_params
    params.require(:activity).permit(:name, :description, :show_time, :value, :place)
  end

  def set_need
    @activity = Activity.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resources)
  	root_path	
  end

  def after_sign_out_path_for(resources)
  	new_user_session_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	layout "admin" 
  before_action :authenticate_user!

	def index
		
	end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  layout "admin" 
  
  before_action :set_need, only: [:edit, :update]

  def index
    @needs = Need.all
  end

  def new
    @need = Need.new
  end

  def create
    @need = Need.new need_params
    if @need.save
      redirect_to needs_path, notice: 'Need was successfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @need.assign_attributes need_params
    if @need.save
      redirect_to needs_path, notice: 'Need was successfully created'
    else
      render :edit
    end
  end

  private
  def need_params
    params.require(:need).permit(:name, :description, :sales_place, :value)
  end

  def set_need
    @need = Need.find params[:id]
  end
end

app/controllers/own_activities_controller.rb
class OwnActivitiesController < ApplicationController
  layout "admin" 

	def index
		@activities = current_user.user_activities
	end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout "admin" 
	before_action :set_user, only: [:edit, :update]

	def index
		@users = User.all
	end

	def new
	end

	def create
	end

	def edit
	end

	def update
		@user.assign_attributes user_params
		if @user.save
			redirect_to users_path, notice: 'User was successfully updated'
		else
			render :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :phone)
	end

	def set_user
		@user = User.find params[:id]
	end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/helpers/own_activities_helper.rb
module OwnActivitiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_activities_table.html.erb
<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Fecha del evento</th>
        <th>Precio estimado del evento</th>
        <th>Lugar del evento</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% activities.each do |activity| %>
        <tr>
          <td><%= activity.name %></td>
          <td><%= activity.description %></td>
          <td><%= activity.show_time %></td>
          <td><%= activity.value %></td>
          <td><%= activity.place %></td>
          <td>
            <%= link_to '<span class="fa fa-pencil"></span>'.html_safe, edit_activity_path(activity), class: "btn btn-default btn-sm", data: { "toggle" => "tooltip" }, title: "Edit" %>
            <%= link_to '<span class="fa fa-plus"></span>'.html_safe, activity_path(activity), class: "btn btn-default btn-sm", data: { "toggle" => "tooltip" }, title: "Unirme" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/activities/_form.html.erb
<%= form_for @activity, url: path, method: method, :html => { class: "form-horizontal validate" } do |f| %>

  <div class="form-group col-sm-12">
    <%= f.label :nombre, class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>


  <div class="form-group col-sm-12">
    <%= f.label :descripcion	, class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.text_field :description, class: "form-control " %>
    </div>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label :lugar  , class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.text_field :place, class: "form-control " %>
    </div>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label :dia_del_evento, class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.date_field :show_time, value: Time.now.strftime('%Y-%m-%d'), class: "form-control " %>
    </div>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label :precio_estimado, class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.text_field :value, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-sm-8 col-xs-12">
      <div class="col-sm-12 text-right">
        <%= f.submit "Save", class: "btn btn-primary", data: {disable_with: 'Please Wait...'}  %>
      </div>
    </div>
  </div>
<% end %>

app/views/activities/_search.html.erb
<%= form_tag "#{}", class: "validate", method: :get, remote: true do %>
  <div class="row form-group">
    <div class="col-sm-5">
      <div class="col-sm-4">
        <%= label_tag :name, "Nombre", class: "control-tag" %>
      </div>
      <div class="col-sm-8">
        <%= text_field_tag :name, nil, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="col-sm-4">
        <%= label_tag :show_time, "Fecha", class: "control-tag" %>
      </div>
      <div class="col-sm-8">
        <%= date_field_tag :show_time, Date.today, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-12">
        <input class="btn btn-default pull-right" type="submit" value="Search">
    </div>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1 class="page-header">Actividades <small>Nuevo</small></h1>
<%= render 'form', activity: @activity, method: :put, path: activitiess_path %>

app/views/activities/index.html.erb
<h1>
  Actividades
  <%= link_to 'Nueva Actividad', new_activity_path, class: "btn btn-primary align-right"  %>
</h1>

<div class="well">
  <%= render 'search' %>
</div>

<div id="table-users">
  <%= render 'activities_table', activities: @activities %>
</div>

app/views/activities/new.html.erb
<h1 class="page-header">Actividades <small>Nuevo</small></h1>
<%= render 'form', activity: @activity, method: :post, path: activities_path %>

app/views/dashboard/index.html.erb
<h1 class="page-header">Dashboard</h1>

<div class="container-fluid">
  <div class="row">

    <div class="col-lg-3 col-md-6">
      <div class="panel panel-yellow">
        <%= link_to users_path do %>
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <i class="fa fa-users fa-5x"></i>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge"><%= User.count %></div>
                <div> Usuarios</div>
              </div>
            </div>
          </div>
          <div class="panel-footer">
            <span class="pull-left">Ver lista de usuarios</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-3 col-md-6">
      <div class="panel panel-red">
        <%= link_to needs_path do %>
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <i class="fa fa-shopping-basket fa-5x"></i>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge"><%= Need.count %></div>
                <div>Necesidades</div>
              </div>
            </div>
          </div>
          <div class="panel-footer">
            <span class="pull-left">Ver lista de necesidades</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-3 col-md-6">
      <div class="panel panel-green">
        <%= link_to activities_path do %>
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <i class="fa fa-calendar fa-5x"></i>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge"><%= Activity.count %></div>
                <div>Actividades</div>
              </div>
            </div>
          </div>
          <div class="panel-footer">
            <span class="pull-left">Ver lista de actividades</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-3 col-md-6">
      <div class="panel panel-blue">
        <%= link_to own_activities_path do %>
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <i class="fa fa-calendar-check-o fa-5x"></i>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge"><%= current_user.user_activities.count %></div>
                <div>Mis Actividades</div>
              </div>
            </div>
          </div>
          <div class="panel-footer">
            <span class="pull-left">Ver lista de mis actividades</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
        <% end %>
      </div>
    </div>    
  </div>
</div>

app/views/needs/_form.html.erb
<%= form_for @need, url: path, method: method, :html => { class: "form-horizontal validate" } do |f| %>

  <div class="form-group col-sm-12">
    <%= f.label :nombre, class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>


  <div class="form-group col-sm-12">
    <%= f.label :descripcion	, class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.text_field :description, class: "form-control " %>
    </div>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label :lugar_de_venta, class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.text_field :sales_place, class: "form-control " %>
    </div>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label :precio, class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.text_field :value, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-sm-8 col-xs-12">
      <div class="col-sm-12 text-right">
        <%= f.submit "Save", class: "btn btn-primary", data: {disable_with: 'Please Wait...'}  %>
      </div>
    </div>
  </div>
<% end %>

app/views/needs/_needs_table.html.erb
<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Lugar de venta</th>
        <th>valor</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% needs.each do |need| %>
        <tr>
          <td><%= need.name %></td>
          <td><%= need.description %></td>
          <td><%= need.sales_place %></td>
          <td><%= need.value %></td>
          <td>
            <%= link_to '<span class="fa fa-pencil"></span>'.html_safe, edit_need_path(need), class: "btn btn-default btn-sm", data: { "toggle" => "tooltip" }, title: "Edit" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/needs/_search.html.erb
<%= form_tag "#{}", class: "validate", method: :get, remote: true do %>
  <div class="row form-group">
    <div class="col-sm-5">
      <div class="col-sm-4">
        <%= label_tag :name, "Nombre", class: "control-tag" %>
      </div>
      <div class="col-sm-8">
        <%= text_field_tag :name, nil, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="col-sm-4">
        <%= label_tag :value, "Precio", class: "control-tag" %>
      </div>
      <div class="col-sm-8">
        <%= text_field_tag :value, nil, class: "form-control" %>
      </div>
    <div class="col-sm-2">
      <div class="col-sm-12">
          <input class="btn btn-default pull-right" type="submit" value="Search">
      </div>
    </div>
  </div>
  </div>
<% end %>

app/views/needs/edit.html.erb
<h1 class="page-header">Necesidades <small>Nuevo</small></h1>
<%= render 'form', need: @need, method: :put, path: needs_path %>

app/views/needs/index.html.erb
<h1>
  Necesidades
  <%= link_to 'Nueva Necesidad', new_need_path, class: "btn btn-primary align-right"  %>
</h1>

<div id="table-users">
  <%= render 'needs_table', needs: @needs %>
</div>

app/views/needs/new.html.erb
<h1 class="page-header">Necesidades <small>Nuevo</small></h1>
<%= render 'form', need: @need, method: :post, path: needs_path %>

app/views/own_activities/_own_activities_table.html.erb
<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Fecha del evento</th>
        <th>Precio estimado del evento</th>
        <th>Lugar del evento</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% activities.each do |my_activity| %>
        <tr>
          <td><%= my_activity.activity.name %></td>
          <td><%= my_activity.activity.description %></td>
          <td><%= my_activity.activity.show_time %></td>
          <td><%= my_activity.activity.value %></td>
          <td><%= my_activity.activity.place %></td>
          <td>
            <%#= link_to '<span class="fa fa-pencil"></span>'.html_safe, edit_activity_path(activity), class: "btn btn-default btn-sm", data: { "toggle" => "tooltip" }, title: "Edit" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/own_activities/_search.html.erb
<%= form_tag "#{}", class: "validate", method: :get, remote: true do %>
  <div class="row form-group">
    <div class="col-sm-5">
      <div class="col-sm-4">
        <%= label_tag :name, "Nombre", class: "control-tag" %>
      </div>
      <div class="col-sm-8">
        <%= text_field_tag :name, nil, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="col-sm-4">
        <%= label_tag :show_time, "Fecha", class: "control-tag" %>
      </div>
      <div class="col-sm-8">
        <%= date_field_tag :show_time, Date.today, class: "form-control" %>
      </div>
    <div class="col-sm-2">
      <div class="col-sm-12">
          <input class="btn btn-default pull-right" type="submit" value="Search">
      </div>
    </div>
  </div>
  </div>
<% end %>

app/views/own_activities/index.html.erb
<h1>
  Mis Actividades
</h1>


<div id="table-users">
  <%= render 'own_activities_table', activities: @activities %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, url: path, method: method, :html => { class: "form-horizontal validate" } do |f| %>

  <div class="form-group col-sm-12">
    <%= f.label :first_name, class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>


  <div class="form-group col-sm-12">
    <%= f.label :last_name	, class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.text_field :last_name, class: "form-control " %>
    </div>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label :phone, class: "col-sm-2 text-left" %>
    <div class="col-sm-6">
      <%= f.text_field :phone, class: "form-control " %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-sm-8 col-xs-12">
      <div class="col-sm-12 text-right">
        <%= f.submit "Save", class: "btn btn-primary", data: {disable_with: 'Please Wait...'}  %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_search.html.erb
<%= form_tag "#{}", class: "validate", method: :get, remote: true do %>
  <div class="row form-group">
    <div class="col-sm-5">
      <div class="col-sm-4">
        <%= label_tag :nombre, "nombre", class: "control-tag" %>
      </div>
      <div class="col-sm-8">
        <%= text_field_tag :first_name, nil, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="col-sm-4">
        <%= label_tag :apellido, "Apellido", class: "control-tag" %>
      </div>
      <div class="col-sm-8">
        <%= text_field_tag :last_name, nil, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-12">
        <input class="btn btn-default pull-right" type="submit" value="Search">
    </div>
  </div>
<% end %>

app/views/users/_users_table.html.erb
<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Email</th>
        <th>Telefono</th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= user.full_name %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<h1 class="page-header">User <small>Editing</small></h1>
<%= render 'form', user: @user, method: :put, path: user_path %>

app/views/users/index.html.erb
<h1>
  Users
</h1>

<div class="well">
  <%= render 'search' %>
</div>

<div id="table-users">
  <%= render 'users_table', users: @users %>
</div>